# Generated by Django 3.2.20 on 2023-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_plugin_uamx_tos_acceptance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]